// SPDX-FileCopyrightText: Copyright 2026 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/supplychain/v1/supplychain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SupplyChainConfig represents the parsed .supplychain.yaml configuration file.
type SupplyChainConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata contains repository and source information.
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Keys contains cryptographic key material for verification.
	Keys          *Keys `protobuf:"bytes,2,opt,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplyChainConfig) Reset() {
	*x = SupplyChainConfig{}
	mi := &file_carabiner_supplychain_v1_supplychain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyChainConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyChainConfig) ProtoMessage() {}

func (x *SupplyChainConfig) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_supplychain_v1_supplychain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyChainConfig.ProtoReflect.Descriptor instead.
func (*SupplyChainConfig) Descriptor() ([]byte, []int) {
	return file_carabiner_supplychain_v1_supplychain_proto_rawDescGZIP(), []int{0}
}

func (x *SupplyChainConfig) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SupplyChainConfig) GetKeys() *Keys {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Metadata holds the repository references for the supply chain.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repositories is a list of collector repository strings.
	Repositories  []string `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_carabiner_supplychain_v1_supplychain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_supplychain_v1_supplychain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_carabiner_supplychain_v1_supplychain_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetRepositories() []string {
	if x != nil {
		return x.Repositories
	}
	return nil
}

// Keys holds key material for verification.
type Keys struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public is a list of public key references (inline PEM data, URLs, or file paths).
	Public        []string `protobuf:"bytes,1,rep,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keys) Reset() {
	*x = Keys{}
	mi := &file_carabiner_supplychain_v1_supplychain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keys) ProtoMessage() {}

func (x *Keys) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_supplychain_v1_supplychain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keys.ProtoReflect.Descriptor instead.
func (*Keys) Descriptor() ([]byte, []int) {
	return file_carabiner_supplychain_v1_supplychain_proto_rawDescGZIP(), []int{2}
}

func (x *Keys) GetPublic() []string {
	if x != nil {
		return x.Public
	}
	return nil
}

var File_carabiner_supplychain_v1_supplychain_proto protoreflect.FileDescriptor

const file_carabiner_supplychain_v1_supplychain_proto_rawDesc = "" +
	"\n" +
	"*carabiner/supplychain/v1/supplychain.proto\x12\x18carabiner.supplychain.v1\"\x87\x01\n" +
	"\x11SupplyChainConfig\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".carabiner.supplychain.v1.MetadataR\bmetadata\x122\n" +
	"\x04keys\x18\x02 \x01(\v2\x1e.carabiner.supplychain.v1.KeysR\x04keys\".\n" +
	"\bMetadata\x12\"\n" +
	"\frepositories\x18\x01 \x03(\tR\frepositories\"\x1e\n" +
	"\x04Keys\x12\x16\n" +
	"\x06public\x18\x01 \x03(\tR\x06publicB\xe0\x01\n" +
	"\x1ccom.carabiner.supplychain.v1B\x10SupplychainProtoP\x01Z,github.com/carabiner-dev/bnd/internal/api/v1\xa2\x02\x03CSX\xaa\x02\x18Carabiner.Supplychain.V1\xca\x02\x18Carabiner\\Supplychain\\V1\xe2\x02$Carabiner\\Supplychain\\V1\\GPBMetadata\xea\x02\x1aCarabiner::Supplychain::V1b\x06proto3"

var (
	file_carabiner_supplychain_v1_supplychain_proto_rawDescOnce sync.Once
	file_carabiner_supplychain_v1_supplychain_proto_rawDescData []byte
)

func file_carabiner_supplychain_v1_supplychain_proto_rawDescGZIP() []byte {
	file_carabiner_supplychain_v1_supplychain_proto_rawDescOnce.Do(func() {
		file_carabiner_supplychain_v1_supplychain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_supplychain_v1_supplychain_proto_rawDesc), len(file_carabiner_supplychain_v1_supplychain_proto_rawDesc)))
	})
	return file_carabiner_supplychain_v1_supplychain_proto_rawDescData
}

var file_carabiner_supplychain_v1_supplychain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_carabiner_supplychain_v1_supplychain_proto_goTypes = []any{
	(*SupplyChainConfig)(nil), // 0: carabiner.supplychain.v1.SupplyChainConfig
	(*Metadata)(nil),          // 1: carabiner.supplychain.v1.Metadata
	(*Keys)(nil),              // 2: carabiner.supplychain.v1.Keys
}
var file_carabiner_supplychain_v1_supplychain_proto_depIdxs = []int32{
	1, // 0: carabiner.supplychain.v1.SupplyChainConfig.metadata:type_name -> carabiner.supplychain.v1.Metadata
	2, // 1: carabiner.supplychain.v1.SupplyChainConfig.keys:type_name -> carabiner.supplychain.v1.Keys
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_carabiner_supplychain_v1_supplychain_proto_init() }
func file_carabiner_supplychain_v1_supplychain_proto_init() {
	if File_carabiner_supplychain_v1_supplychain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_supplychain_v1_supplychain_proto_rawDesc), len(file_carabiner_supplychain_v1_supplychain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_supplychain_v1_supplychain_proto_goTypes,
		DependencyIndexes: file_carabiner_supplychain_v1_supplychain_proto_depIdxs,
		MessageInfos:      file_carabiner_supplychain_v1_supplychain_proto_msgTypes,
	}.Build()
	File_carabiner_supplychain_v1_supplychain_proto = out.File
	file_carabiner_supplychain_v1_supplychain_proto_goTypes = nil
	file_carabiner_supplychain_v1_supplychain_proto_depIdxs = nil
}
